# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: gcr.io/cloud-builders/docker
    script: |
      #!/bin/bash
      apt-get update
      apt-get -y install python3 python3-venv
      python3 -m venv $HOME/venv-python-tests
      . $HOME/venv-python-tests/bin/activate
      pip install --upgrade pip
      cd /workspace/server
      pip install -U -r requirements.txt
      bentoml build
      bentoml containerize stable_diffusion_service:latest -t $LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/bentoml-server-no-model
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'LOCATION=$LOCATION'
      - '_REPO_NAME=$_REPO_NAME'
      - 'HOME=/root'
images: ['$LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/bentoml-server-no-model']
options:
  logging: CLOUD_LOGGING_ONLY